package kotlinx.schema.ksp

/**
 * Shared utilities for source code generation.
 *
 * Provides common functionality used by both ClassSourceCodeGenerator
 * and FunctionSourceCodeGenerator to avoid code duplication.
 */
internal object SourceCodeGeneratorHelpers {
    const val PARAM_WITH_SCHEMA_OBJECT = "withSchemaObject"
    const val OPTION_WITH_SCHEMA_OBJECT = "kotlinx.schema.$PARAM_WITH_SCHEMA_OBJECT"

    /**
     * Determines whether to generate schema object functions/properties.
     *
     * Priority:
     * 1. KSP processor option (kotlinx.schema.withSchemaObject)
     * 2. @Schema annotation parameter (withSchemaObject)
     * 3. Default: false
     */
    fun shouldGenerateSchemaObject(
        options: Map<String, String>,
        parameters: Map<String, Any?>,
    ): Boolean =
        options[OPTION_WITH_SCHEMA_OBJECT]?.let { it == "true" }
            ?: (parameters[PARAM_WITH_SCHEMA_OBJECT] == true)

    /**
     * Escapes a string for use as a Kotlin raw string literal.
     *
     * Handles:
     * - $ characters (replaced with ${'$'})
     * - Triple quotes (escaped as \"\"\")
     *
     * @return String wrapped in triple quotes with proper escaping
     */
    fun String.escapeForKotlinString(): String {
        val escaped = this.replace("$", $$"${'$'}").replace("\"\"\"", "\\\"\\\"\\\"")
        return "\"\"\"" + escaped + "\"\"\""
    }

    /**
     * Generates common file header with suppressions.
     *
     * @param additionalSuppressions Optional list of additional @Suppress annotations
     * @return File header as string
     */
    fun generateFileHeader(
        packageName: String,
        additionalSuppressions: List<String> = emptyList(),
    ): String {
        val baseSuppressions =
            listOf(
                "LongMethod",
                "MaxLineLength",
                "RedundantVisibilityModifier",
                "RemoveRedundantQualifierName",
            )

        val allSuppressions = (baseSuppressions + additionalSuppressions).distinct()

        val suppressionsString = allSuppressions.joinToString(",\n") { "    \"$it\"" }

        return """
            |@file:Suppress(
            |$suppressionsString,
            |)
            |
            |package $packageName
            |
            """.trimMargin()
    }

    /**
     * Generates KDoc comment for generated code.
     *
     * @param targetName The name of the class/function being documented
     * @param description What this generated code provides
     * @return KDoc comment as string
     */
    fun generateKDoc(
        targetName: String,
        description: String,
    ): String =
        """
        |/**
        | * Generated $description for [$targetName].
        | * Generated by kotlinx-schema-ksp processor.
        | */
        | 
        """.trimMargin()
}
