package kotlinx.schema.ksp

internal object SourceCodeGenerator {
    private const val PARAM_WITH_SCHEMA_OBJECT = "withSchemaObject"

    /**
     * A constant representing a configuration key used to specify whether schema generation should include
     * an extension property that provides a schema as a Kotlin object,e.g. `JsonObject`.
     *
     * When enabled (set to "true"), the generated code will include an additional extension property for
     * the target class, allowing direct access to the schema as Kotlin object. Otherwise, only the stringified
     * JSON schema will be generated.
     *
     * This value is typically expected to be provided as an option to the KSP processor and defaults to "false".
     */
    private const val OPTION_WITH_SCHEMA_OBJECT = "kotlinx.schema.$PARAM_WITH_SCHEMA_OBJECT"

    fun generateCode(
        packageName: String,
        classNameWithGenerics: String,
        options: Map<String, String>,
        parameters: Map<String, Any?>,
        schemaString: String,
    ): String =
        buildString {
            // language=kotlin
            append(
                """
                |@file:Suppress(
                |    "MaxLineLength",
                |    "RedundantVisibilityModifier",
                |    "RemoveRedundantQualifierName",
                |    "UnusedReceiverParameter", 
                |)
                |
                |package $packageName
                |
                |/**
                | * Generated extension property providing JSON schema for [$classNameWithGenerics].
                | * Generated by kotlinx-schema-ksp processor.
                | */
                |public val kotlin.reflect.KClass<$classNameWithGenerics>.jsonSchemaString: String
                |    get() =
                |        // language=JSON
                |        ${schemaString.escapeForKotlinString()}
                |
                """.trimMargin(),
            )

            val generateSchemaObject =
                options[OPTION_WITH_SCHEMA_OBJECT]?.let { it == "true" }
                    ?: (parameters[PARAM_WITH_SCHEMA_OBJECT] == true)

            if (generateSchemaObject) {
                append(
                    // language=kotlin
                    """
                |/**
                | * Generated extension property providing JSON schema as JsonObject for [$classNameWithGenerics].
                | * Generated by kotlinx-schema-ksp processor.
                | */
                |public val kotlin.reflect.KClass<$classNameWithGenerics>.jsonSchema: kotlinx.serialization.json.JsonObject
                |    get() = kotlinx.serialization.json.Json.decodeFromString<kotlinx.serialization.json.JsonObject>(jsonSchemaString)
                |
                    """.trimMargin(),
                )
            }
        }

    /**
     * Escapes a string for use as a Kotlin raw string literal, preserving $ and triple quotes.
     */
    private fun String.escapeForKotlinString(): String {
        val escaped = this.replace("$", $$"${'$'}").replace("\"\"\"", "\\\"\\\"\\\"")
        return "\"\"\"" + escaped + "\"\"\""
    }
}
